<?php
/**
 * Provider-independent normalized response object.
 *
 * @package SkyFish\GeminiChat\Providers
 */

namespace SkyFish\GeminiChat\Providers;

// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class ProviderResponse
 *
 * Encapsulates standard response attributes returned by any AI provider.
 */
class ProviderResponse {

	/**
	 * Main text reply generated by the provider.
	 */
	private string $text;

	/**
	 * Identifier of the responding provider (e.g. 'gemini', 'openai', 'claude').
	 */
	private string $provider_id;

	/**
	 * Specific model identifier used (e.g. 'gemini-1.5-flash', 'gpt-4o').
	 */
	private string $model_id;

	/**
	 * Input token count consumed if reported.
	 */
	private ?int $input_tokens;

	/**
	 * Output/completion token count consumed if reported.
	 */
	private ?int $output_tokens;

	/**
	 * Total token count consumed if reported.
	 */
	private ?int $total_tokens;

	/**
	 * Reason why generation finished (e.g. 'stop', 'length', 'safety').
	 */
	private ?string $finish_reason;

	/**
	 * Provider request ID or trace ID if provided.
	 */
	private ?string $request_id;

	/**
	 * Additional raw metadata for diagnostics (zero secrets).
	 *
	 * @var array<string, mixed>
	 */
	private array $metadata;

	/**
	 * ProviderResponse constructor.
	 *
	 * @param string               $text          Generated reply text.
	 * @param string               $provider_id   Provider identifier.
	 * @param string               $model_id      Model identifier.
	 * @param int|null             $input_tokens  Input token count.
	 * @param int|null             $output_tokens Output token count.
	 * @param int|null             $total_tokens  Total token count.
	 * @param string|null          $finish_reason Finish reason.
	 * @param string|null          $request_id    Provider trace ID.
	 * @param array<string, mixed> $metadata      Extra diagnostic metadata.
	 */
	public function __construct(
		string $text,
		string $provider_id,
		string $model_id,
		?int $input_tokens = null,
		?int $output_tokens = null,
		?int $total_tokens = null,
		?string $finish_reason = null,
		?string $request_id = null,
		array $metadata = []
	) {
		$this->text          = $text;
		$this->provider_id   = $provider_id;
		$this->model_id      = $model_id;
		$this->input_tokens  = $input_tokens;
		$this->output_tokens = $output_tokens;
		$this->total_tokens  = $total_tokens ?? ( ( null !== $input_tokens && null !== $output_tokens ) ? ( $input_tokens + $output_tokens ) : null );
		$this->finish_reason = $finish_reason;
		$this->request_id    = $request_id;
		$this->metadata      = $metadata;
	}

	/**
	 * Returns the response text.
	 */
	public function get_text(): string {
		return $this->text;
	}

	/**
	 * Returns the provider identifier.
	 */
	public function get_provider_id(): string {
		return $this->provider_id;
	}

	/**
	 * Returns the model identifier.
	 */
	public function get_model_id(): string {
		return $this->model_id;
	}

	/**
	 * Returns input tokens.
	 */
	public function get_input_tokens(): ?int {
		return $this->input_tokens;
	}

	/**
	 * Returns output tokens.
	 */
	public function get_output_tokens(): ?int {
		return $this->output_tokens;
	}

	/**
	 * Returns total tokens.
	 */
	public function get_total_tokens(): ?int {
		return $this->total_tokens;
	}

	/**
	 * Returns finish reason.
	 */
	public function get_finish_reason(): ?string {
		return $this->finish_reason;
	}

	/**
	 * Returns provider request ID.
	 */
	public function get_request_id(): ?string {
		return $this->request_id;
	}

	/**
	 * Returns diagnostic metadata array.
	 *
	 * @return array<string, mixed>
	 */
	public function get_metadata(): array {
		return $this->metadata;
	}

	/**
	 * Normalizes response to array format.
	 *
	 * @return array<string, mixed>
	 */
	public function to_array(): array {
		return [
			'text'          => $this->text,
			'provider_id'   => $this->provider_id,
			'model_id'      => $this->model_id,
			'tokens'        => [
				'input'  => $this->input_tokens,
				'output' => $this->output_tokens,
				'total'  => $this->total_tokens,
			],
			'finish_reason' => $this->finish_reason,
			'request_id'    => $this->request_id,
			'metadata'      => $this->metadata,
		];
	}
}
